Screen:

    FullImage:
        id: im
        source : 'flow.png'
        keep_ratio : False
        allow_stretch: True
        pos_hint : {"center_x": .5, "center_y": .5}
        size_hint_y : 0.5
        size_hint_x : 1  
        
    MDButton:
        id: btn
        text: ""
        md_bg_color: 0, 0, 0, 0
        pos_hint: { "top": 0.69, "right": 0.902}
        size_hint: 0.775, 0.379
 
     


        

