<LangScreen>:
    
    GridLayout:
        rows: 2
        
        MDRaisedButton:
            id: bueng
            text: "ENG"
            size_hint_x: 1 #from 0.0 to 1.0
            on_press: root.manager.current = "search_screen"

            
        MDRaisedButton:
            id: buit
            text: "IT"
            size_hint_x: 1 #from 0.0 to 1.0
            on_press: root.manager.current = "search_screen"